// Code generated by ogen, DO NOT EDIT.
package oas

type CartGetRes interface {
	cartGetRes()
}

type CartPostRes interface {
	cartPostRes()
}

type CartProductIdDeleteRes interface {
	cartProductIdDeleteRes()
}

type CartProductIdPutRes interface {
	cartProductIdPutRes()
}

type DeliveryGetRes interface {
	deliveryGetRes()
}

type DeliveryPostRes interface {
	deliveryPostRes()
}

type OrdersGetRes interface {
	ordersGetRes()
}

type OrdersOrderIdGetRes interface {
	ordersOrderIdGetRes()
}

type OrdersPostRes interface {
	ordersPostRes()
}

type PaymentsGetRes interface {
	paymentsGetRes()
}

type PaymentsPostRes interface {
	paymentsPostRes()
}

type ProductsProductIdReviewsGetRes interface {
	productsProductIdReviewsGetRes()
}

type ProductsProductIdReviewsPostRes interface {
	productsProductIdReviewsPostRes()
}

type UsersProfileGetRes interface {
	usersProfileGetRes()
}

type UsersProfilePutRes interface {
	usersProfilePutRes()
}

type UsersRegisterPostRes interface {
	usersRegisterPostRes()
}
