// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CartGet implements GET /cart operation.
//
// View the contents of the cart.
//
// GET /cart
func (UnimplementedHandler) CartGet(ctx context.Context) (r CartGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CartPost implements POST /cart operation.
//
// Add a product to the cart.
//
// POST /cart
func (UnimplementedHandler) CartPost(ctx context.Context, req *CartItemCreate) (r CartPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CartProductIdDelete implements DELETE /cart/{productId} operation.
//
// Remove a product from the cart.
//
// DELETE /cart/{productId}
func (UnimplementedHandler) CartProductIdDelete(ctx context.Context, params CartProductIdDeleteParams) (r CartProductIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CartProductIdPut implements PUT /cart/{productId} operation.
//
// Update the quantity of a product in the cart.
//
// PUT /cart/{productId}
func (UnimplementedHandler) CartProductIdPut(ctx context.Context, req *CartProductIdPutReq, params CartProductIdPutParams) (r CartProductIdPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CategoriesCategoryIdDelete implements DELETE /categories/{categoryId} operation.
//
// Delete a specific category (Admin only).
//
// DELETE /categories/{categoryId}
func (UnimplementedHandler) CategoriesCategoryIdDelete(ctx context.Context, params CategoriesCategoryIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// CategoriesCategoryIdPut implements PUT /categories/{categoryId} operation.
//
// Update a specific category (Admin only).
//
// PUT /categories/{categoryId}
func (UnimplementedHandler) CategoriesCategoryIdPut(ctx context.Context, req *CategoryUpdate, params CategoriesCategoryIdPutParams) error {
	return ht.ErrNotImplemented
}

// CategoriesGet implements GET /categories operation.
//
// Retrieve a list of all categories.
//
// GET /categories
func (UnimplementedHandler) CategoriesGet(ctx context.Context) (r []Category, _ error) {
	return r, ht.ErrNotImplemented
}

// CategoriesPost implements POST /categories operation.
//
// Add a new category (Admin only).
//
// POST /categories
func (UnimplementedHandler) CategoriesPost(ctx context.Context, req *CategoryCreate) error {
	return ht.ErrNotImplemented
}

// DeliveryGet implements GET /delivery operation.
//
// Track delivery status.
//
// GET /delivery
func (UnimplementedHandler) DeliveryGet(ctx context.Context) (r DeliveryGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeliveryPost implements POST /delivery operation.
//
// Choose delivery method and input delivery address.
//
// POST /delivery
func (UnimplementedHandler) DeliveryPost(ctx context.Context, req *DeliveryChoice) (r DeliveryPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersGet implements GET /orders operation.
//
// Get user's order history.
//
// GET /orders
func (UnimplementedHandler) OrdersGet(ctx context.Context) (r OrdersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersOrderIdGet implements GET /orders/{orderId} operation.
//
// View order details.
//
// GET /orders/{orderId}
func (UnimplementedHandler) OrdersOrderIdGet(ctx context.Context, params OrdersOrderIdGetParams) (r OrdersOrderIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersPost implements POST /orders operation.
//
// Create a new order.
//
// POST /orders
func (UnimplementedHandler) OrdersPost(ctx context.Context, req *OrderCreate) (r OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PaymentsGet implements GET /payments operation.
//
// Get user's payment history.
//
// GET /payments
func (UnimplementedHandler) PaymentsGet(ctx context.Context) (r PaymentsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PaymentsPost implements POST /payments operation.
//
// Initiate a payment.
//
// POST /payments
func (UnimplementedHandler) PaymentsPost(ctx context.Context, req *PaymentInitiate) (r PaymentsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProductsGet implements GET /products operation.
//
// Retrieve a list of products.
//
// GET /products
func (UnimplementedHandler) ProductsGet(ctx context.Context, params ProductsGetParams) (r []Product, _ error) {
	return r, ht.ErrNotImplemented
}

// ProductsPost implements POST /products operation.
//
// Add a new product (Admin only).
//
// POST /products
func (UnimplementedHandler) ProductsPost(ctx context.Context, req *ProductCreate) error {
	return ht.ErrNotImplemented
}

// ProductsProductIdDelete implements DELETE /products/{productId} operation.
//
// Delete a specific product (Admin only).
//
// DELETE /products/{productId}
func (UnimplementedHandler) ProductsProductIdDelete(ctx context.Context, params ProductsProductIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// ProductsProductIdGet implements GET /products/{productId} operation.
//
// Retrieve details of a specific product.
//
// GET /products/{productId}
func (UnimplementedHandler) ProductsProductIdGet(ctx context.Context, params ProductsProductIdGetParams) (r *Product, _ error) {
	return r, ht.ErrNotImplemented
}

// ProductsProductIdImagePost implements POST /products/{productId}/image operation.
//
// Upload an image for a specific product (Admin only).
//
// POST /products/{productId}/image
func (UnimplementedHandler) ProductsProductIdImagePost(ctx context.Context, req *ProductsProductIdImagePostReq, params ProductsProductIdImagePostParams) error {
	return ht.ErrNotImplemented
}

// ProductsProductIdPut implements PUT /products/{productId} operation.
//
// Update a specific product (Admin only).
//
// PUT /products/{productId}
func (UnimplementedHandler) ProductsProductIdPut(ctx context.Context, req *ProductUpdate, params ProductsProductIdPutParams) error {
	return ht.ErrNotImplemented
}

// ProductsProductIdReviewsGet implements GET /products/{productId}/reviews operation.
//
// Get reviews of a product.
//
// GET /products/{productId}/reviews
func (UnimplementedHandler) ProductsProductIdReviewsGet(ctx context.Context, params ProductsProductIdReviewsGetParams) (r ProductsProductIdReviewsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProductsProductIdReviewsPost implements POST /products/{productId}/reviews operation.
//
// Add a review to a product.
//
// POST /products/{productId}/reviews
func (UnimplementedHandler) ProductsProductIdReviewsPost(ctx context.Context, req *ReviewInput, params ProductsProductIdReviewsPostParams) (r ProductsProductIdReviewsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersChangePasswordPost implements POST /users/change-password operation.
//
// Change password for authenticated user.
//
// POST /users/change-password
func (UnimplementedHandler) UsersChangePasswordPost(ctx context.Context, req *UsersChangePasswordPostReq) error {
	return ht.ErrNotImplemented
}

// UsersConfirmEmailPost implements POST /users/confirm-email operation.
//
// Confirm email using the provided token.
//
// POST /users/confirm-email
func (UnimplementedHandler) UsersConfirmEmailPost(ctx context.Context, req *UsersConfirmEmailPostReq) error {
	return ht.ErrNotImplemented
}

// UsersForgotPasswordPost implements POST /users/forgot-password operation.
//
// Request password reset.
//
// POST /users/forgot-password
func (UnimplementedHandler) UsersForgotPasswordPost(ctx context.Context, req *UsersForgotPasswordPostReq) error {
	return ht.ErrNotImplemented
}

// UsersLoginGoogleCallbackGet implements GET /users/login/google/callback operation.
//
// Handle Google authentication callback.
//
// GET /users/login/google/callback
func (UnimplementedHandler) UsersLoginGoogleCallbackGet(ctx context.Context) (r *UsersLoginGoogleCallbackGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersLoginGoogleGet implements GET /users/login/google operation.
//
// Start authentication with Google.
//
// GET /users/login/google
func (UnimplementedHandler) UsersLoginGoogleGet(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// UsersLoginPost implements POST /users/login operation.
//
// Authenticate user.
//
// POST /users/login
func (UnimplementedHandler) UsersLoginPost(ctx context.Context, req *UsersLoginPostReq) (r *UsersLoginPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersProfileGet implements GET /users/profile operation.
//
// Get user's profile information.
//
// GET /users/profile
func (UnimplementedHandler) UsersProfileGet(ctx context.Context) (r UsersProfileGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersProfilePut implements PUT /users/profile operation.
//
// Update user's profile information.
//
// PUT /users/profile
func (UnimplementedHandler) UsersProfilePut(ctx context.Context, req *UserUpdate) (r UsersProfilePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersRegisterPost implements POST /users/register operation.
//
// Register a new user.
//
// POST /users/register
func (UnimplementedHandler) UsersRegisterPost(ctx context.Context, req *UserRegistration) (r UsersRegisterPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersResetPasswordPost implements POST /users/reset-password operation.
//
// Reset password using the provided token.
//
// POST /users/reset-password
func (UnimplementedHandler) UsersResetPasswordPost(ctx context.Context, req *UsersResetPasswordPostReq) error {
	return ht.ErrNotImplemented
}
